export const GET_FLIGHT_LOCATIONS = "GET_FLIGHT_LOCATIONS";
export const GET_FLEETS = "GET_FLEETS";
export const GET_FLIGHTS = "GET_FLIGHTS";

export const CREATE_FLIGHT_LOCATION = "CREATE_FLIGHT_LOCATION";
export const CREATE_FLIGHT = "CREATE_FLIGHT";

export const UPDATE_FLIGHT_LOCATION = "UPDATE_FLIGHT_LOCATION";
export const UPDATE_FLIGHT = "UPDATE_FLIGHT";

export const DELETE_FLIGHT_LOCATION = "DELETE_FLIGHT_LOCATION";
export const DELETE_FLIGHT = "DELETE_FLIGHT";
