export const GET_FLIGHT_LOCATIONS = "GET_FLIGHT_LOCATIONS";
export const GET_FLIGTS = "GET_FLIGHTS";

export const CREATE_FLIGHT_LOCATION = "CREATE_FLIGHT_LOCATION";
export const CREATE_FLIGHT = "CREATE_FLIGHT";
