export const GET_COUNTRY_LIST = "GET_COUNTRY_LIST"

export const API_SUCCESS = "API_SUCCESS"
export const API_ERROR = "API_ERROR"

// Login constants
export const LOGIN_USER = "LOGIN_USER"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const RESET_LOGIN_STATE = "RESET_LOGIN_STATE";

export const AUTHENTICATED = "AUTHENTICATED"

// Register constants
export const REGISTER_USER = "REGISTER_USER"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
export const RESET_REGISTER_STATE = "RESET_REGISTER_STATE";

// Email Confirmation constants
export const EMAIL_CONFIRMATION = "EMAIL_CONFIRMATION"
export const EMAIL_CONFIRMATION_SUCCESS = "EMAIL_CONFIRMATION_SUCCESS";
export const EMAIL_CONFIRMATION_FAILURE = "EMAIL_CONFIRMATION_FAILURE";
export const RESET_EMAIL_CONFIRMATION_STATE = "RESET_EMAIL_CONFIRMATION_STATE";

// Contact Details constants
export const ADD_CONTACT_DETAILS = "ADD_CONTACT_DETAILS"
export const ADD_CONTACT_DETAILS_SUCCESS = "ADD_CONTACT_DETAILS_SUCCESS";
export const ADD_CONTACT_DETAILS_FAILURE = "ADD_CONTACT_DETAILS_FAILURE";
export const RESET_CONTACT_DETAILS_STATE = "RESET_CONTACT_DETAILS_STATE";

// Forgot Password constants
export const FORGOT_PASSWORD = "FORGOT_PASSWORD"
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAILURE = "FORGOT_PASSWORD_FAILURE";
export const RESET_FORGOT_PASSWORD_STATE = "RESET_FORGOT_PASSWORD_STATE";

// Forgot password confirmation constants
export const FORGOT_PASSWORD_CONFIRMATION = "FORGOT_PASSWORD_CONFIRMATION"
export const FORGOT_PASSWORD_CONFIRMATION_SUCCESS = "FORGOT_PASSWORD_CONFIRMATION_SUCCESS";
export const FORGOT_PASSWORD_CONFIRMATION_FAILURE = "FORGOT_PASSWORD_CONFIRMATION_FAILURE";
export const RESET_FORGOT_PASSWORD_CONFIRMATION_STATE = "RESET_FORGOT_PASSWORD_CONFIRMATION_STATE";

// Reset Password constants
export const RESET_PASSWORD = "RESET_PASSWORD"
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILURE = "RESET_PASSWORD_FAILURE";
export const RESET_RESET_PASSWORD_STATE = "RESET_RESET_PASSWORD_STATE";

// Change Password constants
export const CHANGE_PASSWORD = "CHANGE_PASSWORD"
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAILURE = "CHANGE_PASSWORD_FAILURE";
export const RESET_CHANGE_PASSWORD_STATE = "RESET_CHANGE_PASSWORD_STATE";


