export const GET_PAST_BOOKINGS = "GET_PAST_BOOKINGS"
export const GET_UPCOMING_TRIPS = "GET_UPCOMING_TRIPS"

export const GET_USER_DETAILS_BY_EMAIL_SUCCESS = "GET_USER_DETAILS_BY_EMAIL_SUCCESS";
export const GET_USER_DETAILS_BY_EMAIL_FAILURE = "GET_USER_DETAILS_BY_EMAIL_FAILURE";

export const UPDATE_USER_DETAILS_SUCCESS = "UPDATE_USER_DETAILS_SUCCESS";
export const UPDATE_USER_DETAILS_FAILURE = "UPDATE_USER_DETAILS_FAILURE";