export const GET_PAST_BOOKINGS = "GET_PAST_BOOKINGS"
export const GET_UPCOMING_TRIPS = "GET_UPCOMING_TRIPS"

export const GET_USER_DETAILS_BY_EMAIL_SUCCESS = "GET_USER_DETAILS_BY_EMAIL_SUCCESS";
export const GET_USER_DETAILS_BY_EMAIL_FAILURE = "GET_USER_DETAILS_BY_EMAIL_FAILURE";

export const UPDATE_USER_DETAILS_SUCCESS = "UPDATE_USER_DETAILS_SUCCESS";
export const UPDATE_USER_DETAILS_FAILURE = "UPDATE_USER_DETAILS_FAILURE";

export const CANCEL_BOOKING_SUCCESS = "CANCEL_BOOKING_SUCCESS"
export const CANCEL_BOOKING_FAILURE = "CANCEL_BOOKING_FAILURE"

export const GET_PAST_BOOKINGS_SUCCESS = "GET_PAST_BOOKINGS_SUCCESS"
export const GET_PAST_BOOKINGS_FAILURE = "GET_PAST_BOOKINGS_FAILURE"

export const GET_UPCOMING_TRIPS_SUCCESS = "GET_UPCOMING_TRIPS_SUCCESS"
export const GET_UPCOMING_TRIPS_FAILURE = "GET_UPCOMING_TRIPS_FAILURE"